# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wakalog < Formula
  desc ""
  homepage "https://github.com/Youngtard/homebrew-wakalog"
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/Youngtard/wakalogs/releases/download/v0.1.3/wakalogs_Darwin_x86_64.tar.gz"
      sha256 "2b7a668f976878f70540e197b16fa2f66c7cee19a5fd44b25b1e066ca3b892e2"

      def install
        bin.install "wakalogs"
      end
    end
    on_arm do
      url "https://github.com/Youngtard/wakalogs/releases/download/v0.1.3/wakalogs_Darwin_arm64.tar.gz"
      sha256 "b252139988db81f3c199194501938c4fd4435877aa3c19da5657afbcd4ebcb68"

      def install
        bin.install "wakalogs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Youngtard/wakalogs/releases/download/v0.1.3/wakalogs_Linux_x86_64.tar.gz"
        sha256 "fcd193f4db2df82c49522759e093988c73c8ac348166657011f54dd564135752"

        def install
          bin.install "wakalogs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Youngtard/wakalogs/releases/download/v0.1.3/wakalogs_Linux_arm64.tar.gz"
        sha256 "76e0fe065f83afa0549bca1cce6c792e346e949077efdce0c3a8b814cb0060b6"

        def install
          bin.install "wakalogs"
        end
      end
    end
  end
end
