# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wakalog < Formula
  desc ""
  homepage "https://github.com/Youngtard/homebrew-wakalog"
  version "0.1.6"

  on_macos do
    on_intel do
      url "https://github.com/Youngtard/wakalog/releases/download/v0.1.6/wakalog_Darwin_x86_64.tar.gz"
      sha256 "a86b1a7513cd693007b4af19589618a4cb872da74cfecfee4ffe81389fb8cbcf"

      def install
        bin.install "wakalog"
      end
    end
    on_arm do
      url "https://github.com/Youngtard/wakalog/releases/download/v0.1.6/wakalog_Darwin_arm64.tar.gz"
      sha256 "f05937565cd76bb3106ee4db34a03c2854707f06e9b242fad9955d7011119006"

      def install
        bin.install "wakalog"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Youngtard/wakalog/releases/download/v0.1.6/wakalog_Linux_x86_64.tar.gz"
        sha256 "32bce665b69c90db4f66c7354c46f65e16e56d4809428900785cce7a4275c2e8"

        def install
          bin.install "wakalog"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Youngtard/wakalog/releases/download/v0.1.6/wakalog_Linux_arm64.tar.gz"
        sha256 "6257777327d6530f3b5e56d1a04621f6ac1eaaaa28b829e2af1743a97528f0d6"

        def install
          bin.install "wakalog"
        end
      end
    end
  end
end
